name: Pull Request

on: [pull_request]

env:
  DOCKER_IMAGE_USER: cyberryteam
  DOCKER_IMAGE_NAME: epitech-xp-calculator

jobs:

  docker:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker build . \
            -t $DOCKER_IMAGE_USER/$DOCKER_IMAGE_NAME:latest
